import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/header.js";

export default function Home() {
  const homeHeaderProps = {
    title: "Welcome to Next Book Store!",
    subTitle: "Get started by checking our newly arrived books",
    buttonText: "New Arrivals",
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Book Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header {...homeHeaderProps} />
      </main>
    </div>
  );
}
